version: "3.9"

services:
  app:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/app
    command: sh -c "npm run start"
    ports:
      - 3000:3000
    stdin_open: true

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - .env
    container_name: db
    ports:
      - 3306:3306

  go:
    build: ./server
    volumes:
      - ./server:/app
    container_name: server
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db
